use crate::utils::u32_from;
const fn to_u16(h: u8, l: u8) -> u16 {
    ((h as u16) << 8) | (l as u16)
}
#[derive(Debug, Clone, Copy)]
pub enum MidiError {
    InvalidFileFormat(u8), // 0: HEADER / 1: Track
    InvalidHeader,
    UnknownFormat,
    LengthError,
    UnknownEventFormat(u8),
    UnknownEvent,
    Custom(&'static str),
}
impl std::fmt::Display for MidiError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::InvalidFileFormat(s) => write!(
                f,
                "Invalid File Format: {} is broken",
                if *s == 0 {
                    "Header"
                } else if *s == 1 {
                    "Track"
                } else {
                    "unknown"
                }
            ),
            Self::InvalidHeader => write!(f, "Invalid Header"),
            Self::UnknownFormat => write!(f, "Unknown Format"),
            Self::LengthError => write!(f, "Length Error"),
            Self::UnknownEventFormat(e) => write!(f, "Unknown Event Format: {:#x}", e),
            Self::UnknownEvent => write!(f, "Unknown Event"),
            Self::Custom(s) => write!(f, "{s}"),
        }
    }
}
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum Format {
    Format0,
    Format1,
    Format2,
}
impl TryFrom<u16> for Format {
    type Error = MidiError;
    fn try_from(value: u16) -> Result<Self, Self::Error> {
        match value {
            0 => Ok(Self::Format0),
            1 => Ok(Self::Format1),
            2 => Ok(Self::Format2),
            _ => Err(MidiError::UnknownFormat),
        }
    }
}
#[derive(Debug)]
pub struct MidiInfo {
    header: MidiHeader,
    // track: u32,
    events: Vec<MidiEvent>,
}

impl MidiInfo {
    pub fn get_header(&self) -> &MidiHeader {
        &self.header
    }
    pub fn get_events(&self) -> &Vec<MidiEvent> {
        &self.events
    }
}

#[derive(Debug)]
pub struct MidiHeader {
    format: Format,
    time_unit: u16,
    tracks: u16,
}
impl MidiHeader {
    pub fn is_format0(&self) -> bool {
        self.format == Format::Format0
    }
}
#[derive(Debug)]
pub struct MidiEvent {
    delta_time: usize,
    ch: u8,
    data: Vec<u8>,
}
impl MidiEvent {
    pub fn get_ch(&self) -> u8 {
        self.ch
    }
    pub fn get_data(&self) -> &Vec<u8> {
        &self.data
    }
}
impl TryFrom<&[u8]> for MidiHeader {
    type Error = MidiError;
    fn try_from(data: &[u8]) -> Result<Self, Self::Error> {
        if data[0..4] != [0x4d, 0x54, 0x68, 0x64] {
            return Err(MidiError::InvalidFileFormat(0));
        }
        if u32_from(&data[4..]) != 6 {
            return Err(MidiError::InvalidHeader);
        }
        let format = Format::try_from(to_u16(data[8], data[9]))?;
        let tracks = to_u16(data[12], data[13]);
        let time_unit = to_u16(data[10], data[11]);
        Ok(Self {
            format,
            time_unit,
            tracks,
        })
    }
}

impl TryFrom<&[u8]> for MidiInfo {
    type Error = MidiError;
    fn try_from(data: &[u8]) -> Result<Self, Self::Error> {
        let header = MidiHeader::try_from(data)?;
        let mut events = Vec::new();
        if data[14..18] != [0x4d, 0x54, 0x72, 0x6b] {
            return Err(MidiError::InvalidFileFormat(1));
        }
        let track_size = u32_from(&data[18..]);
        let raw_events = &data[22..];
        let mut i = 0;
        while i < raw_events.len() {
            let (delta_time, len) = get_variable_value(&raw_events[i..])?;
            i += len;
            let ch = raw_events[i] & 0x0f;
            let event = raw_events[i] & 0xf0;
            // this switch process is generated by Gemini
            // NOTE: イベント情報が欠落しているので、参照する際は、各イベントの情報を追加すること
            // 0xC0や0xA0などが落ちている。
            match event {
                0x80 | 0x90 | 0xA0 | 0xB0 | 0xE0 => {
                    let mut event_data = vec![0; 2];
                    event_data[0] = raw_events[i + 1];
                    event_data[1] = raw_events[i + 2];
                    i += 3;
                    events.push(MidiEvent {
                        delta_time,
                        ch,
                        data: event_data,
                    });
                }
                0xC0 | 0xD0 => {
                    let mut event_data = vec![0; 1];
                    event_data[0] = raw_events[i + 1];
                    i += 2;
                    events.push(MidiEvent {
                        delta_time,
                        ch,
                        data: event_data,
                    });
                }
                0xf0 => {
                    match raw_events[i] {
                        0xf0 | 0xf7 => {
                            let mut event_data = Vec::new();
                            i += 1;
                            while raw_events[i] != 0xf7 {
                                event_data.push(raw_events[i]);
                                i += 1;
                            }
                            events.push(MidiEvent {
                                delta_time,
                                ch: 0,
                                data: event_data,
                            });
                            i += 1; // 0xf7をスキップ
                        }
                        0xff => {
                            // Meta Event
                            let meta_type = raw_events[i + 1];
                            let (meta_len, len_bytes) = get_variable_value(&raw_events[i + 2..])?;
                            let mut event_data = vec![0; meta_len];
                            event_data.copy_from_slice(
                                &raw_events[i + 2 + len_bytes..i + 2 + len_bytes + meta_len],
                            );
                            i += 2 + len_bytes + meta_len;
                            events.push(MidiEvent {
                                delta_time,
                                // Non Channel
                                ch: 0,
                                data: event_data,
                            });
                        }
                        e => return Err(MidiError::UnknownEventFormat(e)),
                    }
                }
                _ => return Err(MidiError::UnknownEvent),
            }
        }
        Ok(Self { header, events })
    }
}

// return: (data, length)
fn get_variable_value(data: &[u8]) -> Result<(usize, usize), MidiError> {
    let mut value = 0;
    let mut len = 0;
    loop {
        // データが足りない場合のエラーハンドリング
        if len >= data.len() {
            return Err(MidiError::LengthError); // もしくはより適切なエラー
        }
        // 4バイトを超えるVLQは不正
        if len > 4 {
            return Err(MidiError::LengthError);
        }

        let byte = data[len] as usize;
        len += 1;

        // 既存の値を7ビット左シフトし、現在のバイトの下位7ビットを合成する
        value = (value << 7) | (byte & 0x7F);

        // 現在のバイトのMSBが0であれば、これが最後のバイト
        if byte & 0x80 == 0 {
            break;
        }
    }
    Ok((value, len))
}
